name: Discord Alerts

on:
  push:
    branches: [ main ]  # Aciona apenas no branch main

jobs:
  send-discord-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: Sniddl/discord-commits@v1.6  # Usando action pública
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}  # Sintaxe correta
          template: "avatar-with-link"
          include-extras: true
